export const Base_URI = "http://localhost:5173"
export const AUTHAPI_URI = "http://localhost:8000/api/auth"
export const APPLICATIONAPI_URI = "http://localhost:8000/api/application"
export const COMPANYAPI_URI = "http://localhost:8000/api/company"
export const JOBAPI_URI = "http://localhost:8000/api/job"
