export const Base_URI = "http://localhost:5173"
export const AUTHAPI_URI = "https://jobprotal-backend.onrender.com/api/auth"
export const APPLICATIONAPI_URI = "https://jobprotal-backend.onrender.com/api/application"
export const COMPANYAPI_URI = "https://jobprotal-backend.onrender.com/api/company"
export const JOBAPI_URI = "https://jobprotal-backend.onrender.com/api/job"
